export const PROFILE = {
  fullName: "Mohammed Jaseer",
  headline: "Accountant · Operations · Procurement | UAE experience (Abu Dhabi)",
  phone: "+971 56 454 9259",
  email: "mohammedjaseerkp11@gmail.com",
  linkedin: "https://linkedin.com/in/jaseerkp/",
  locationNow: "India",
  targetLocation: "UAE (Abu Dhabi / Dubai) — visa valid until Dec 2027, available to relocate",
  summary:
    "Versatile Accounting and Operations professional with UAE experience across accounting, finance, procurement, purchasing, project coordination, client management, staff supervision, and business operations in the interior fit-out industry. Joined Introyale Interiors LLC (Abu Dhabi) as an Accountant and, within the first 5–6 months, took on additional responsibilities across company operations, procurement, project coordination, client management, staff supervision, and HR-related activities.",
  targetRoles: [
    "Accountant",
    "Accounts Assistant",
    "Accounts Payable",
    "Accounts Receivable",
    "Finance Officer",
    "Procurement Officer",
    "Purchasing Officer",
    "Buyer",
    "Operations Coordinator",
    "Project Coordinator",
    "Administrator",
    "Business Support",
  ],
  keywords: [
    "accounting",
    "bookkeeping",
    "accounts payable",
    "accounts receivable",
    "invoicing",
    "vat",
    "procurement",
    "purchasing",
    "sourcing",
    "supplier",
    "quotation",
    "rfq",
    "lpo",
    "operations",
    "project coordination",
    "staff supervision",
    "fit-out",
    "hospitality",
    "hotel",
    "uae",
    "abu dhabi",
    "dubai",
  ],
  skills: [
    {
      title: "Accounting & Finance",
      body: "Accounting and Bookkeeping; AP; AR; Purchase and Sales Entries; Invoicing; Receivables Follow-up; VAT Preparation and Filing",
    },
    {
      title: "Procurement & Purchasing",
      body: "Supplier Sourcing; Quotation Comparison; Negotiation; Material Sourcing; Cost Control; Delivery Coordination",
    },
    {
      title: "Project & Operations",
      body: "Project Coordination; Scheduling; Workforce Coordination; Staff Supervision (~25–30); Deadline Management",
    },
    {
      title: "Client Coordination",
      body: "RFQ Management; Quotation Preparation; LPO Processing; Hotel Client Coordination; Cross-functional follow-up",
    },
  ],
  experience: [
    {
      company: "Introyale Interiors LLC",
      place: "Abu Dhabi, UAE",
      title: "Accountant → Operations, Procurement & Project Coordination",
      dates: "27 Oct 2023 – 16 May 2026",
      bullets: [
        "Managed day-to-day accounting including purchase/sales entries, AP, AR, invoicing, and receivables follow-up.",
        "Prepared VAT-related records and handled VAT preparation and filing activities.",
        "Ran the quotation workflow from client RFQ through site visits, pricing, submission, LPO, and execution.",
        "Sourced suppliers after approved LPOs, compared quotations, negotiated prices, and coordinated deliveries to project deadlines.",
        "Coordinated interior fit-out projects for hotel clients; scheduled ~25–30 staff and aligned purchasing, housekeeping, finance, operations, and engineering.",
      ],
    },
    {
      company: "Tubees Foods",
      place: "India",
      title: "Junior Accounts Assistant",
      dates: "2022 – 2023",
      bullets: [
        "Assisted with daily accounting transactions, invoices, payment follow-ups, and office administration.",
      ],
    },
  ],
  education: [
    { school: "University of Calicut", detail: "Bachelor of Commerce (B.Com)", dates: "2019 – 2021" },
    { school: "HSS Anamangad", detail: "Higher Secondary Education", dates: "2017 – 2018" },
  ],
  languages: [
    { name: "Malayalam", level: "Native" },
    { name: "English", level: "Fluent" },
    { name: "Hindi", level: "Basic" },
  ],
};

export const TITLE_HINTS = [
  "account",
  "financ",
  "audit",
  "bookkeep",
  "payable",
  "receivable",
  "procure",
  "purchas",
  "buyer",
  "sourc",
  "operation",
  "coordina",
  "administ",
  "office",
  "project",
  "logistic",
  "supply",
  "inventory",
  "warehouse",
  "billing",
  "payroll",
  "vat",
  "tax",
];
